### PR TITLE
feat: create allow list for camelCased SVG attributes

### PR DESCRIPTION
**Pull request by mgdodge**
This addresses issue #62 in the vue 3 branch. Would need to be backported to vue 2 branch if approved.

### CODE REVIEW

**Comment by elevatebart** [comment]
Thank you @mgdodge I really appreciate it.

Do you think you could make it so that if I am using SVG attributes outside of <SVG> tags, it fails?

If not I will merge this anyway.

**Comment by mgdodge** [comment]
Not sure what you mean - you want it to only allow these attributes when the tag is an SVG tag? If that is the request, I specifically do not want that. The reason is that I need this for a vue component where the base tag in the template section is an SVG. That means I need to allow these attributes on the component tag itself. For example:

```vue
// my-component.vue
<script>
export default {
  props: ['iconName'],
  // other code here
}
</script>
<template>
  <svg>
    <g v-if="iconName === 'foo'"> <!-- foo icon content --></g>
    <g v-else><!-- other icon content --></g>
  </svg>
</template>
```

```vue
// vue-live demo
<template>
  <my-component preserveAspectRatio="xMidYMid slice" />
  <my-component iconName="foo" />
</template>
```

As illustrated here, the SVG attributes would be entirely valid, even expected, on the main component tag, which would then be passed along.

**Comment by elevatebart** [comment]
Good point, I will merge this.

I will also need to add a prop to have a custom list of accepted valid props.

It's always useful to make exceptions.

**Pull request merged**
