### PR TITLE
feat: make code & language accessible for custom layout

### PR DESCRIPTION
**Pull request by r4fx**
Hi @elevatebart! 
I appreciate your work for this repo and whole ecosystem (`vue-docgen-api`, `vue-inbrowser-compiler`, etc...), big thanks for that!

Please consider about this PR, this could be helpful for cases like mine, where I need to have an access to `code` and `lang` in my wrapper, because I need to do a bit more things in the view.

Cheers!

### CODE REVIEW

**Comment by elevatebart** [comment]
Hello Rafal,

That sure is useful, can you add a note for that in the demo website?

Can you as well update your commit messages to match the angular convention? It helps semantic release to decide the new version. In your case it is a new feature ;)

Thank you so much for the compliment.

Bart Ledoux
Twitter: @bartledoux
Github, Gitter, Discord: @elevatebart

**Comment by r4fx** [comment]
Should be ready, please check if it's ok for You :)

**Comment by elevatebart** [comment]
great job !!

**Pull request merged**
